-- ----------------------------------------------------------------------------------------------------------------
-- Generated by LLBLGen Pro v5.7  Build: 5.7.1
-- SQL Server DDL Script generated from project: HnD
-- Project filename: C:\MyProjects\VS.NET Projects\GitHub\FransBouma\HnD\LLBLGenPro Projects\HnD.llblgenproj
-- Script generated on: 23-Sep-2020 11:31.19
--
-- This is a Create script for creating a NEW data model. If you want DDL SQL for updating an existing model,
-- please create an Update script instead. 
--
-- This script might create schemas, which requires you to assign a proper user to the schema. Adjust the CREATE SCHEMA
-- statements below, if any, to avoid errors at runtime. Schemas aren't dropped in the DROP section.
--
--      >>>>> WARNING <<<<<
--      This is a CREATE script, with DROP statements for the existing tables, foreign keys and other constraints
--      This means that existing tables, data, constraints and other elements in the catalog/schemas addressed
--      are deleted. Use this Create script only to create new schemas with tables/constraints and other elements.
--
-- ----------------------------------------------------------------------------------------------------------------
-- ###############################################################################################################
-- DROP statements for existing elements. 
-- ###############################################################################################################
-- DROP statements for dropping existing elements with the same names as the ones created are commented out below. 
-- If you want to enable these statements for DROPping the existing elements first (which will remove all the data
-- in these existing elements), uncomment these statements by removing the two comment markers /* and */

-- Remove the comment marker on the NEXT line to enable DROP statements to remove existing elements
/* 

-- ----------------------------------------------------------------------------------------------------------------
-- Catalog 'HnD'
-- ----------------------------------------------------------------------------------------------------------------

USE [HnD]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- DROP Foreign keys
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE [dbo].[Attachment] DROP CONSTRAINT [FK_Attachment_Message]
GO

ALTER TABLE [dbo].[AuditDataCore] DROP CONSTRAINT [TF_AuditDataCore_TF_AuditAction_FK1]
GO

ALTER TABLE [dbo].[AuditDataCore] DROP CONSTRAINT [TF_User_TF_AuditDataCore_FK1]
GO

ALTER TABLE [dbo].[AuditDataMessageRelated] DROP CONSTRAINT [TF_AuditDataMessageRelated_TF_AuditDataCore_FK1]
GO

ALTER TABLE [dbo].[AuditDataMessageRelated] DROP CONSTRAINT [TF_AuditDataMessageRelated_TF_Message_FK1]
GO

ALTER TABLE [dbo].[AuditDataThreadRelated] DROP CONSTRAINT [TF_AuditDataThreadRelated_TF_AuditDataCore_FK1]
GO

ALTER TABLE [dbo].[AuditDataThreadRelated] DROP CONSTRAINT [TF_AuditDataThreadRelated_TF_Thread_FK1]
GO

ALTER TABLE [dbo].[Bookmark] DROP CONSTRAINT [TF_Thread_TF_Bookmark_FK]
GO

ALTER TABLE [dbo].[Bookmark] DROP CONSTRAINT [TF_User_TF_Bookmark_FK]
GO

ALTER TABLE [dbo].[Forum] DROP CONSTRAINT [FK_Forum_SupportQueue]
GO

ALTER TABLE [dbo].[Forum] DROP CONSTRAINT [TF_Section_TF_Forum_FK1]
GO

ALTER TABLE [dbo].[ForumRoleForumActionRight] DROP CONSTRAINT [TF_ActionRight_TF_ForumRoleForumActionRight_FK1]
GO

ALTER TABLE [dbo].[ForumRoleForumActionRight] DROP CONSTRAINT [TF_Forum_TF_ForumRoleActionRight_FK1]
GO

ALTER TABLE [dbo].[ForumRoleForumActionRight] DROP CONSTRAINT [TF_Role_TF_ForumRoleActionRight_FK1]
GO

ALTER TABLE [dbo].[IPBan] DROP CONSTRAINT [FK_TF_IPBan_TF_User]
GO

ALTER TABLE [dbo].[Message] DROP CONSTRAINT [TF_Thread_TF_Message_FK1]
GO

ALTER TABLE [dbo].[Message] DROP CONSTRAINT [TF_User_TF_Message_FK1]
GO

ALTER TABLE [dbo].[PasswordResetToken] DROP CONSTRAINT [FK_9f1eaa94f1fb774bb77aad91f5d]
GO

ALTER TABLE [dbo].[RoleAuditAction] DROP CONSTRAINT [TF_AuditAction_TF_RoleAuditAction_FK1]
GO

ALTER TABLE [dbo].[RoleAuditAction] DROP CONSTRAINT [TF_Role_TF_RoleAuditAction_FK1]
GO

ALTER TABLE [dbo].[RoleSystemActionRight] DROP CONSTRAINT [TF_ActionRight_TF_RoleSystemActionRight_FK1]
GO

ALTER TABLE [dbo].[RoleSystemActionRight] DROP CONSTRAINT [TF_Role_TF_RoleSystemActionRight_FK1]
GO

ALTER TABLE [dbo].[RoleUser] DROP CONSTRAINT [TF_Role_TF_RoleUser_FK1]
GO

ALTER TABLE [dbo].[RoleUser] DROP CONSTRAINT [TF_User_TF_RoleUser_FK1]
GO

ALTER TABLE [dbo].[SupportQueueThread] DROP CONSTRAINT [FK_SupportQueueThread_SupportQueue]
GO

ALTER TABLE [dbo].[SupportQueueThread] DROP CONSTRAINT [FK_SupportQueueThread_Thread]
GO

ALTER TABLE [dbo].[SupportQueueThread] DROP CONSTRAINT [FK_SupportQueueThread_User]
GO

ALTER TABLE [dbo].[SupportQueueThread] DROP CONSTRAINT [FK_SupportQueueThread_User1]
GO

ALTER TABLE [dbo].[SystemData] DROP CONSTRAINT [FK_TF_SystemData_TF_Role]
GO

ALTER TABLE [dbo].[SystemData] DROP CONSTRAINT [FK_TF_SystemData_TF_Role1]
GO

ALTER TABLE [dbo].[Thread] DROP CONSTRAINT [TF_Forum_TF_Thread_FK1]
GO

ALTER TABLE [dbo].[Thread] DROP CONSTRAINT [TF_User_TF_Thread_FK1]
GO

ALTER TABLE [dbo].[ThreadSubscription] DROP CONSTRAINT [FK_ThreadSubscription_Thread]
GO

ALTER TABLE [dbo].[ThreadSubscription] DROP CONSTRAINT [FK_ThreadSubscription_User]
GO

ALTER TABLE [dbo].[User] DROP CONSTRAINT [TF_UserTitle_TF_User_FK1]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- DROP tables for schema 'dbo' 
-- ----------------------------------------------------------------------------------------------------------------

DROP TABLE [dbo].[ActionRight]
GO

DROP TABLE [dbo].[Attachment]
GO

DROP TABLE [dbo].[AuditAction]
GO

DROP TABLE [dbo].[AuditDataCore]
GO

DROP TABLE [dbo].[AuditDataMessageRelated]
GO

DROP TABLE [dbo].[AuditDataThreadRelated]
GO

DROP TABLE [dbo].[Bookmark]
GO

DROP TABLE [dbo].[Forum]
GO

DROP TABLE [dbo].[ForumRoleForumActionRight]
GO

DROP TABLE [dbo].[IPBan]
GO

DROP TABLE [dbo].[Message]
GO

DROP TABLE [dbo].[PasswordResetToken]
GO

DROP TABLE [dbo].[Role]
GO

DROP TABLE [dbo].[RoleAuditAction]
GO

DROP TABLE [dbo].[RoleSystemActionRight]
GO

DROP TABLE [dbo].[RoleUser]
GO

DROP TABLE [dbo].[Section]
GO

DROP TABLE [dbo].[SupportQueue]
GO

DROP TABLE [dbo].[SupportQueueThread]
GO

DROP TABLE [dbo].[SystemData]
GO

DROP TABLE [dbo].[Thread]
GO

DROP TABLE [dbo].[ThreadSubscription]
GO

DROP TABLE [dbo].[User]
GO

DROP TABLE [dbo].[UserTitle]
GO
*/
-- Remove the comment marker on the PREVIOUS line to enable DROP statements to remove existing elements

-- ###############################################################################################################
-- Create statements for catalogs, schemas, tables and sequences
-- ###############################################################################################################

-- ----------------------------------------------------------------------------------------------------------------
-- Catalog 'HnD'
-- ----------------------------------------------------------------------------------------------------------------

USE master
GO
CREATE DATABASE [HnD] /* ON PRIMARY (NAME=HnD_dat, FILENAME='c:\mycatalogs\HnD.mdf', SIZE=10MB) */
GO


USE [HnD]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Schema 'dbo'
-- ----------------------------------------------------------------------------------------------------------------

-- -------[ Tables ]-----------------------------------------------------------------------------------------------

CREATE TABLE [dbo].[ActionRight] 
(
	[ActionRightID] [int] NOT NULL, 
	[ActionRightDescription] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[AppliesToForum] [bit] NOT NULL, 
	[AppliesToSystem] [bit] NOT NULL 
)
GO

CREATE TABLE [dbo].[Attachment] 
(
	[AttachmentID] [int] IDENTITY (1,1) NOT NULL, 
	[MessageID] [int] NOT NULL, 
	[Filename] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Approved] [bit] NOT NULL, 
	[Filecontents] [image] NOT NULL, 
	[Filesize] [int] NOT NULL, 
	[AddedOn] [datetime] NOT NULL 
)
GO

CREATE TABLE [dbo].[AuditAction] 
(
	[AuditActionID] [int] NOT NULL, 
	[AuditActionDescription] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL 
)
GO

CREATE TABLE [dbo].[AuditDataCore] 
(
	[AuditDataID] [int] IDENTITY (1,1) NOT NULL, 
	[AuditActionID] [int] NOT NULL, 
	[UserID] [int] NOT NULL, 
	[AuditedOn] [datetime] NOT NULL 
)
GO

CREATE TABLE [dbo].[AuditDataMessageRelated] 
(
	[AuditDataID] [int] NOT NULL, 
	[MessageID] [int] NOT NULL 
)
GO

CREATE TABLE [dbo].[AuditDataThreadRelated] 
(
	[AuditDataID] [int] NOT NULL, 
	[ThreadID] [int] NOT NULL 
)
GO

CREATE TABLE [dbo].[Bookmark] 
(
	[ThreadID] [int] NOT NULL, 
	[UserID] [int] NOT NULL 
)
GO

CREATE TABLE [dbo].[Forum] 
(
	[ForumID] [int] IDENTITY (1,1) NOT NULL, 
	[SectionID] [int] NOT NULL, 
	[ForumName] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[ForumDescription] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[ForumLastPostingDate] [datetime] NULL, 
	[HasRSSFeed] [bit] NOT NULL, 
	[DefaultSupportQueueID] [int] NULL, 
	[OrderNo] [smallint] NOT NULL, 
	[MaxAttachmentSize] [int] NULL, 
	[MaxNoOfAttachmentsPerMessage] [smallint] NULL, 
	[NewThreadWelcomeText] [ntext] NULL, 
	[NewThreadWelcomeTextAsHTML] [ntext] NULL 
)
GO

CREATE TABLE [dbo].[ForumRoleForumActionRight] 
(
	[ForumID] [int] NOT NULL, 
	[RoleID] [int] NOT NULL, 
	[ActionRightID] [int] NOT NULL 
)
GO

CREATE TABLE [dbo].[IPBan] 
(
	[IPBanID] [int] IDENTITY (1,1) NOT NULL, 
	[IPSegment1] [tinyint] NOT NULL, 
	[IPSegment2] [tinyint] NOT NULL, 
	[IPSegment3] [tinyint] NOT NULL, 
	[IPSegment4] [tinyint] NOT NULL, 
	[Range] [tinyint] NOT NULL, 
	[IPBanSetByUserID] [int] NOT NULL, 
	[IPBanSetOn] [datetime] NOT NULL, 
	[Reason] [ntext] NOT NULL 
)
GO

CREATE TABLE [dbo].[Message] 
(
	[MessageID] [int] IDENTITY (1,1) NOT NULL, 
	[PostingDate] [datetime] NOT NULL, 
	[PostedByUserID] [int] NOT NULL, 
	[ThreadID] [int] NOT NULL, 
	[PostedFromIP] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[ChangeTrackerStamp] [timestamp] NOT NULL, 
	[MessageText] [ntext] NULL, 
	[MessageTextAsHTML] [ntext] NULL 
)
GO

CREATE TABLE [dbo].[PasswordResetToken] 
(
	[UserID] [int] NOT NULL, 
	[PasswordResetToken] [uniqueidentifier] NOT NULL, 
	[PasswordResetRequestedOn] [datetime] NOT NULL 
)
GO

CREATE TABLE [dbo].[Role] 
(
	[RoleID] [int] IDENTITY (1,1) NOT NULL, 
	[RoleDescription] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL 
)
GO

CREATE TABLE [dbo].[RoleAuditAction] 
(
	[AuditActionID] [int] NOT NULL, 
	[RoleID] [int] NOT NULL 
)
GO

CREATE TABLE [dbo].[RoleSystemActionRight] 
(
	[RoleID] [int] NOT NULL, 
	[ActionRightID] [int] NOT NULL 
)
GO

CREATE TABLE [dbo].[RoleUser] 
(
	[RoleID] [int] NOT NULL, 
	[UserID] [int] NOT NULL 
)
GO

CREATE TABLE [dbo].[Section] 
(
	[SectionID] [int] IDENTITY (1,1) NOT NULL, 
	[SectionName] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[SectionDescription] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[OrderNo] [smallint] NOT NULL 
)
GO

CREATE TABLE [dbo].[SupportQueue] 
(
	[QueueID] [int] IDENTITY (1,1) NOT NULL, 
	[QueueName] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[QueueDescription] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[OrderNo] [smallint] NOT NULL 
)
GO

CREATE TABLE [dbo].[SupportQueueThread] 
(
	[QueueID] [int] NOT NULL, 
	[ThreadID] [int] NOT NULL, 
	[PlacedInQueueByUserID] [int] NOT NULL, 
	[PlacedInQueueOn] [datetime] NOT NULL, 
	[ClaimedByUserID] [int] NULL, 
	[ClaimedOn] [datetime] NULL 
)
GO

CREATE TABLE [dbo].[SystemData] 
(
	[ID] [int] IDENTITY (1,1) NOT NULL, 
	[DefaultRoleNewUser] [int] NOT NULL, 
	[AnonymousRole] [int] NOT NULL, 
	[DefaultUserTitleNewUser] [int] NOT NULL, 
	[HoursThresholdForActiveThreads] [smallint] NOT NULL, 
	[PageSizeSearchResults] [smallint] NOT NULL, 
	[MinNumberOfThreadsToFetch] [smallint] NOT NULL, 
	[MinNumberOfNonStickyVisibleThreads] [smallint] NOT NULL, 
	[SendReplyNotifications] [bit] NOT NULL 
)
GO

CREATE TABLE [dbo].[Thread] 
(
	[ThreadID] [int] IDENTITY (1,1) NOT NULL, 
	[ForumID] [int] NOT NULL, 
	[Subject] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[StartedByUserID] [int] NOT NULL, 
	[ThreadLastPostingDate] [datetime] NULL, 
	[IsSticky] [bit] NOT NULL, 
	[IsClosed] [bit] NOT NULL, 
	[MarkedAsDone] [bit] NOT NULL, 
	[NumberOfViews] [int] NULL, 
	[Memo] [ntext] NULL 
)
GO

CREATE TABLE [dbo].[ThreadSubscription] 
(
	[UserID] [int] NOT NULL, 
	[ThreadID] [int] NOT NULL 
)
GO

CREATE TABLE [dbo].[User] 
(
	[UserID] [int] IDENTITY (1,1) NOT NULL, 
	[NickName] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Password] [nvarchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[IsBanned] [bit] NOT NULL, 
	[IPNumber] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Signature] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
	[IconURL] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
	[EmailAddress] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
	[UserTitleID] [int] NOT NULL, 
	[DateOfBirth] [datetime] NULL, 
	[Occupation] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
	[Location] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
	[Website] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
	[JoinDate] [datetime] NULL, 
	[AmountOfPostings] [int] NULL, 
	[EmailAddressIsPublic] [bit] NULL, 
	[LastVisitedDate] [datetime] NULL, 
	[AutoSubscribeToThread] [bit] NULL, 
	[DefaultNumberOfMessagesPerPage] [smallint] NULL 
)
GO

CREATE TABLE [dbo].[UserTitle] 
(
	[UserTitleID] [int] IDENTITY (1,1) NOT NULL, 
	[UserTitleDescription] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL 
)
GO

-- ###############################################################################################################
-- Create statements for Primary key constraints, Foreign key constraints, Unique constraints and Default Values
-- ###############################################################################################################
-- ----------------------------------------------------------------------------------------------------------------
-- Catalog 'HnD'
-- ----------------------------------------------------------------------------------------------------------------

USE [HnD]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Primary Key constraints for schema 'dbo'
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE [dbo].[ActionRight] WITH NOCHECK 
	ADD CONSTRAINT [TF_ActionRight_PK] PRIMARY KEY CLUSTERED 
	( 
		[ActionRightID] 
	)
GO

ALTER TABLE [dbo].[Attachment] WITH NOCHECK 
	ADD CONSTRAINT [PK_Attachment] PRIMARY KEY CLUSTERED 
	( 
		[AttachmentID] 
	)
GO

ALTER TABLE [dbo].[AuditAction] WITH NOCHECK 
	ADD CONSTRAINT [TF_AuditAction_PK] PRIMARY KEY CLUSTERED 
	( 
		[AuditActionID] 
	)
GO

ALTER TABLE [dbo].[AuditDataCore] WITH NOCHECK 
	ADD CONSTRAINT [TF_AuditDataCore_PK] PRIMARY KEY CLUSTERED 
	( 
		[AuditDataID] 
	)
GO

ALTER TABLE [dbo].[AuditDataMessageRelated] WITH NOCHECK 
	ADD CONSTRAINT [TF_AuditDataMessageRelated_PK] PRIMARY KEY CLUSTERED 
	( 
		[AuditDataID] 
	)
GO

ALTER TABLE [dbo].[AuditDataThreadRelated] WITH NOCHECK 
	ADD CONSTRAINT [TF_AuditDataThreadRelated_PK] PRIMARY KEY CLUSTERED 
	( 
		[AuditDataID] 
	)
GO

ALTER TABLE [dbo].[Bookmark] WITH NOCHECK 
	ADD CONSTRAINT [TF_Bookmark_PK] PRIMARY KEY CLUSTERED 
	( 
		[ThreadID], [UserID] 
	)
GO

ALTER TABLE [dbo].[Forum] WITH NOCHECK 
	ADD CONSTRAINT [TF_Forum_PK] PRIMARY KEY CLUSTERED 
	( 
		[ForumID] 
	)
GO

ALTER TABLE [dbo].[ForumRoleForumActionRight] WITH NOCHECK 
	ADD CONSTRAINT [TF_ForumRoleActionRight_PK] PRIMARY KEY CLUSTERED 
	( 
		[ForumID], [RoleID], [ActionRightID] 
	)
GO

ALTER TABLE [dbo].[IPBan] WITH NOCHECK 
	ADD CONSTRAINT [PK_TF_IPBan] PRIMARY KEY CLUSTERED 
	( 
		[IPBanID] 
	)
GO

ALTER TABLE [dbo].[Message] WITH NOCHECK 
	ADD CONSTRAINT [TF_Message_PK] PRIMARY KEY CLUSTERED 
	( 
		[MessageID] 
	)
GO

ALTER TABLE [dbo].[PasswordResetToken] WITH NOCHECK 
	ADD CONSTRAINT [PK_446ab684e0591442b16f78fc437] PRIMARY KEY CLUSTERED 
	( 
		[UserID] 
	)
GO

ALTER TABLE [dbo].[Role] WITH NOCHECK 
	ADD CONSTRAINT [TF_Role_PK] PRIMARY KEY CLUSTERED 
	( 
		[RoleID] 
	)
GO

ALTER TABLE [dbo].[RoleAuditAction] WITH NOCHECK 
	ADD CONSTRAINT [TF_RoleAuditAction_PK] PRIMARY KEY CLUSTERED 
	( 
		[AuditActionID], [RoleID] 
	)
GO

ALTER TABLE [dbo].[RoleSystemActionRight] WITH NOCHECK 
	ADD CONSTRAINT [TF_RoleSystemActionRight_PK] PRIMARY KEY CLUSTERED 
	( 
		[RoleID], [ActionRightID] 
	)
GO

ALTER TABLE [dbo].[RoleUser] WITH NOCHECK 
	ADD CONSTRAINT [TF_RoleUser_PK] PRIMARY KEY CLUSTERED 
	( 
		[RoleID], [UserID] 
	)
GO

ALTER TABLE [dbo].[Section] WITH NOCHECK 
	ADD CONSTRAINT [TF_Section_PK] PRIMARY KEY CLUSTERED 
	( 
		[SectionID] 
	)
GO

ALTER TABLE [dbo].[SupportQueue] WITH NOCHECK 
	ADD CONSTRAINT [PK_SupportQueue] PRIMARY KEY CLUSTERED 
	( 
		[QueueID] 
	)
GO

ALTER TABLE [dbo].[SupportQueueThread] WITH NOCHECK 
	ADD CONSTRAINT [PK_SupportQueueThread] PRIMARY KEY CLUSTERED 
	( 
		[QueueID], [ThreadID] 
	)
GO

ALTER TABLE [dbo].[SystemData] WITH NOCHECK 
	ADD CONSTRAINT [PK_TF_SystemData] PRIMARY KEY CLUSTERED 
	( 
		[ID] 
	)
GO

ALTER TABLE [dbo].[Thread] WITH NOCHECK 
	ADD CONSTRAINT [TF_Thread_PK] PRIMARY KEY CLUSTERED 
	( 
		[ThreadID] 
	)
GO

ALTER TABLE [dbo].[ThreadSubscription] WITH NOCHECK 
	ADD CONSTRAINT [PK_ThreadSubscription] PRIMARY KEY CLUSTERED 
	( 
		[UserID], [ThreadID] 
	)
GO

ALTER TABLE [dbo].[User] WITH NOCHECK 
	ADD CONSTRAINT [TF_User_PK] PRIMARY KEY CLUSTERED 
	( 
		[UserID] 
	)
GO

ALTER TABLE [dbo].[UserTitle] WITH NOCHECK 
	ADD CONSTRAINT [TF_UserTitle_PK] PRIMARY KEY CLUSTERED 
	( 
		[UserTitleID] 
	)
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Unique constraints for schema 'dbo'
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE [dbo].[SupportQueueThread] 
	ADD CONSTRAINT [UC_SupportQueueThread_ThreadID] UNIQUE NONCLUSTERED
	(
		[ThreadID] 
	)
GO

ALTER TABLE [dbo].[User] 
	ADD CONSTRAINT [TF_User_NickName_U2] UNIQUE NONCLUSTERED
	(
		[NickName] 
	)
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Default values for schema 'dbo'
-- ----------------------------------------------------------------------------------------------------------------
ALTER TABLE [dbo].[Forum] 
	ADD CONSTRAINT [DV_Forum_HasRSSFeed] DEFAULT ((1)) FOR [HasRSSFeed]
GO
ALTER TABLE [dbo].[Forum] 
	ADD CONSTRAINT [DV_Forum_OrderNo] DEFAULT ((0)) FOR [OrderNo]
GO
ALTER TABLE [dbo].[Forum] 
	ADD CONSTRAINT [DV_Forum_MaxAttachmentSize] DEFAULT ((512)) FOR [MaxAttachmentSize]
GO
ALTER TABLE [dbo].[Forum] 
	ADD CONSTRAINT [DV_Forum_MaxNoOfAttachmentsPerMessage] DEFAULT ((1)) FOR [MaxNoOfAttachmentsPerMessage]
GO
ALTER TABLE [dbo].[IPBan] 
	ADD CONSTRAINT [DV_IPBan_IPSegment1] DEFAULT ((0)) FOR [IPSegment1]
GO
ALTER TABLE [dbo].[IPBan] 
	ADD CONSTRAINT [DV_IPBan_IPSegment2] DEFAULT ((0)) FOR [IPSegment2]
GO
ALTER TABLE [dbo].[IPBan] 
	ADD CONSTRAINT [DV_IPBan_IPSegment3] DEFAULT ((0)) FOR [IPSegment3]
GO
ALTER TABLE [dbo].[IPBan] 
	ADD CONSTRAINT [DV_IPBan_IPSegment4] DEFAULT ((0)) FOR [IPSegment4]
GO
ALTER TABLE [dbo].[IPBan] 
	ADD CONSTRAINT [DV_IPBan_IPBanSetOn] DEFAULT ((getdate())) FOR [IPBanSetOn]
GO
ALTER TABLE [dbo].[Message] 
	ADD CONSTRAINT [DV_Message_PostedFromIP] DEFAULT ('('')') FOR [PostedFromIP]
GO
ALTER TABLE [dbo].[Section] 
	ADD CONSTRAINT [DV_Section_OrderNo] DEFAULT ((0)) FOR [OrderNo]
GO
ALTER TABLE [dbo].[SystemData] 
	ADD CONSTRAINT [DV_SystemData_DefaultUserTitleNewUser] DEFAULT ((0)) FOR [DefaultUserTitleNewUser]
GO
ALTER TABLE [dbo].[SystemData] 
	ADD CONSTRAINT [DV_SystemData_HoursThresholdForActiveThreads] DEFAULT ((48)) FOR [HoursThresholdForActiveThreads]
GO
ALTER TABLE [dbo].[SystemData] 
	ADD CONSTRAINT [DV_SystemData_PageSizeSearchResults] DEFAULT ((50)) FOR [PageSizeSearchResults]
GO
ALTER TABLE [dbo].[SystemData] 
	ADD CONSTRAINT [DV_SystemData_MinNumberOfThreadsToFetch] DEFAULT ((25)) FOR [MinNumberOfThreadsToFetch]
GO
ALTER TABLE [dbo].[SystemData] 
	ADD CONSTRAINT [DV_SystemData_MinNumberOfNonStickyVisibleThreads] DEFAULT ((5)) FOR [MinNumberOfNonStickyVisibleThreads]
GO
ALTER TABLE [dbo].[SystemData] 
	ADD CONSTRAINT [DV_SystemData_SendReplyNotifications] DEFAULT ((1)) FOR [SendReplyNotifications]
GO
ALTER TABLE [dbo].[Thread] 
	ADD CONSTRAINT [DV_Thread_MarkedAsDone] DEFAULT ((1)) FOR [MarkedAsDone]
GO
ALTER TABLE [dbo].[Thread] 
	ADD CONSTRAINT [DV_Thread_NumberOfViews] DEFAULT ((0)) FOR [NumberOfViews]
GO
ALTER TABLE [dbo].[User] 
	ADD CONSTRAINT [DV_User_JoinDate] DEFAULT ((getdate())) FOR [JoinDate]
GO
ALTER TABLE [dbo].[User] 
	ADD CONSTRAINT [DV_User_AmountOfPostings] DEFAULT ((0)) FOR [AmountOfPostings]
GO
ALTER TABLE [dbo].[User] 
	ADD CONSTRAINT [DV_User_EmailAddressIsPublic] DEFAULT ((0)) FOR [EmailAddressIsPublic]
GO
ALTER TABLE [dbo].[User] 
	ADD CONSTRAINT [DV_User_AutoSubscribeToThread] DEFAULT ((1)) FOR [AutoSubscribeToThread]
GO
ALTER TABLE [dbo].[User] 
	ADD CONSTRAINT [DV_User_DefaultNumberOfMessagesPerPage] DEFAULT ((25)) FOR [DefaultNumberOfMessagesPerPage]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- All foreign Key constraints
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE [dbo].[Attachment] 
	ADD CONSTRAINT [FK_Attachment_Message] FOREIGN KEY
	(
		[MessageID] 
	)
	REFERENCES [dbo].[Message]
	(
		[MessageID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[AuditDataCore] 
	ADD CONSTRAINT [TF_AuditDataCore_TF_AuditAction_FK1] FOREIGN KEY
	(
		[AuditActionID] 
	)
	REFERENCES [dbo].[AuditAction]
	(
		[AuditActionID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[AuditDataCore] 
	ADD CONSTRAINT [TF_User_TF_AuditDataCore_FK1] FOREIGN KEY
	(
		[UserID] 
	)
	REFERENCES [dbo].[User]
	(
		[UserID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[AuditDataMessageRelated] 
	ADD CONSTRAINT [TF_AuditDataMessageRelated_TF_AuditDataCore_FK1] FOREIGN KEY
	(
		[AuditDataID] 
	)
	REFERENCES [dbo].[AuditDataCore]
	(
		[AuditDataID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[AuditDataMessageRelated] 
	ADD CONSTRAINT [TF_AuditDataMessageRelated_TF_Message_FK1] FOREIGN KEY
	(
		[MessageID] 
	)
	REFERENCES [dbo].[Message]
	(
		[MessageID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[AuditDataThreadRelated] 
	ADD CONSTRAINT [TF_AuditDataThreadRelated_TF_AuditDataCore_FK1] FOREIGN KEY
	(
		[AuditDataID] 
	)
	REFERENCES [dbo].[AuditDataCore]
	(
		[AuditDataID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[AuditDataThreadRelated] 
	ADD CONSTRAINT [TF_AuditDataThreadRelated_TF_Thread_FK1] FOREIGN KEY
	(
		[ThreadID] 
	)
	REFERENCES [dbo].[Thread]
	(
		[ThreadID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[Bookmark] 
	ADD CONSTRAINT [TF_Thread_TF_Bookmark_FK] FOREIGN KEY
	(
		[ThreadID] 
	)
	REFERENCES [dbo].[Thread]
	(
		[ThreadID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[Bookmark] 
	ADD CONSTRAINT [TF_User_TF_Bookmark_FK] FOREIGN KEY
	(
		[UserID] 
	)
	REFERENCES [dbo].[User]
	(
		[UserID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[Forum] 
	ADD CONSTRAINT [FK_Forum_SupportQueue] FOREIGN KEY
	(
		[DefaultSupportQueueID] 
	)
	REFERENCES [dbo].[SupportQueue]
	(
		[QueueID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[Forum] 
	ADD CONSTRAINT [TF_Section_TF_Forum_FK1] FOREIGN KEY
	(
		[SectionID] 
	)
	REFERENCES [dbo].[Section]
	(
		[SectionID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[ForumRoleForumActionRight] 
	ADD CONSTRAINT [TF_ActionRight_TF_ForumRoleForumActionRight_FK1] FOREIGN KEY
	(
		[ActionRightID] 
	)
	REFERENCES [dbo].[ActionRight]
	(
		[ActionRightID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[ForumRoleForumActionRight] 
	ADD CONSTRAINT [TF_Forum_TF_ForumRoleActionRight_FK1] FOREIGN KEY
	(
		[ForumID] 
	)
	REFERENCES [dbo].[Forum]
	(
		[ForumID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[ForumRoleForumActionRight] 
	ADD CONSTRAINT [TF_Role_TF_ForumRoleActionRight_FK1] FOREIGN KEY
	(
		[RoleID] 
	)
	REFERENCES [dbo].[Role]
	(
		[RoleID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[IPBan] 
	ADD CONSTRAINT [FK_TF_IPBan_TF_User] FOREIGN KEY
	(
		[IPBanSetByUserID] 
	)
	REFERENCES [dbo].[User]
	(
		[UserID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[Message] 
	ADD CONSTRAINT [TF_Thread_TF_Message_FK1] FOREIGN KEY
	(
		[ThreadID] 
	)
	REFERENCES [dbo].[Thread]
	(
		[ThreadID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[Message] 
	ADD CONSTRAINT [TF_User_TF_Message_FK1] FOREIGN KEY
	(
		[PostedByUserID] 
	)
	REFERENCES [dbo].[User]
	(
		[UserID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[PasswordResetToken] 
	ADD CONSTRAINT [FK_9f1eaa94f1fb774bb77aad91f5d] FOREIGN KEY
	(
		[UserID] 
	)
	REFERENCES [dbo].[User]
	(
		[UserID] 
	)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[RoleAuditAction] 
	ADD CONSTRAINT [TF_AuditAction_TF_RoleAuditAction_FK1] FOREIGN KEY
	(
		[AuditActionID] 
	)
	REFERENCES [dbo].[AuditAction]
	(
		[AuditActionID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[RoleAuditAction] 
	ADD CONSTRAINT [TF_Role_TF_RoleAuditAction_FK1] FOREIGN KEY
	(
		[RoleID] 
	)
	REFERENCES [dbo].[Role]
	(
		[RoleID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[RoleSystemActionRight] 
	ADD CONSTRAINT [TF_ActionRight_TF_RoleSystemActionRight_FK1] FOREIGN KEY
	(
		[ActionRightID] 
	)
	REFERENCES [dbo].[ActionRight]
	(
		[ActionRightID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[RoleSystemActionRight] 
	ADD CONSTRAINT [TF_Role_TF_RoleSystemActionRight_FK1] FOREIGN KEY
	(
		[RoleID] 
	)
	REFERENCES [dbo].[Role]
	(
		[RoleID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[RoleUser] 
	ADD CONSTRAINT [TF_Role_TF_RoleUser_FK1] FOREIGN KEY
	(
		[RoleID] 
	)
	REFERENCES [dbo].[Role]
	(
		[RoleID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[RoleUser] 
	ADD CONSTRAINT [TF_User_TF_RoleUser_FK1] FOREIGN KEY
	(
		[UserID] 
	)
	REFERENCES [dbo].[User]
	(
		[UserID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[SupportQueueThread] 
	ADD CONSTRAINT [FK_SupportQueueThread_SupportQueue] FOREIGN KEY
	(
		[QueueID] 
	)
	REFERENCES [dbo].[SupportQueue]
	(
		[QueueID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[SupportQueueThread] 
	ADD CONSTRAINT [FK_SupportQueueThread_Thread] FOREIGN KEY
	(
		[ThreadID] 
	)
	REFERENCES [dbo].[Thread]
	(
		[ThreadID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[SupportQueueThread] 
	ADD CONSTRAINT [FK_SupportQueueThread_User] FOREIGN KEY
	(
		[PlacedInQueueByUserID] 
	)
	REFERENCES [dbo].[User]
	(
		[UserID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[SupportQueueThread] 
	ADD CONSTRAINT [FK_SupportQueueThread_User1] FOREIGN KEY
	(
		[ClaimedByUserID] 
	)
	REFERENCES [dbo].[User]
	(
		[UserID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[SystemData] 
	ADD CONSTRAINT [FK_TF_SystemData_TF_Role] FOREIGN KEY
	(
		[DefaultRoleNewUser] 
	)
	REFERENCES [dbo].[Role]
	(
		[RoleID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[SystemData] 
	ADD CONSTRAINT [FK_TF_SystemData_TF_Role1] FOREIGN KEY
	(
		[AnonymousRole] 
	)
	REFERENCES [dbo].[Role]
	(
		[RoleID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[Thread] 
	ADD CONSTRAINT [TF_Forum_TF_Thread_FK1] FOREIGN KEY
	(
		[ForumID] 
	)
	REFERENCES [dbo].[Forum]
	(
		[ForumID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[Thread] 
	ADD CONSTRAINT [TF_User_TF_Thread_FK1] FOREIGN KEY
	(
		[StartedByUserID] 
	)
	REFERENCES [dbo].[User]
	(
		[UserID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[ThreadSubscription] 
	ADD CONSTRAINT [FK_ThreadSubscription_Thread] FOREIGN KEY
	(
		[ThreadID] 
	)
	REFERENCES [dbo].[Thread]
	(
		[ThreadID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[ThreadSubscription] 
	ADD CONSTRAINT [FK_ThreadSubscription_User] FOREIGN KEY
	(
		[UserID] 
	)
	REFERENCES [dbo].[User]
	(
		[UserID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[User] 
	ADD CONSTRAINT [TF_UserTitle_TF_User_FK1] FOREIGN KEY
	(
		[UserTitleID] 
	)
	REFERENCES [dbo].[UserTitle]
	(
		[UserTitleID] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO



