//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using SD.HnD.DALAdapter.HelperClasses;
using SD.HnD.DALAdapter.FactoryClasses;
using SD.HnD.DALAdapter.RelationClasses;
using System.ComponentModel.DataAnnotations;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace SD.HnD.DALAdapter.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'ForumRoleForumActionRight'.<br/><br/></summary>
	[Serializable]
	public partial class ForumRoleForumActionRightEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private ActionRightEntity _actionRight;
		private ForumEntity _forum;
		private RoleEntity _role;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static ForumRoleForumActionRightEntityStaticMetaData _staticMetaData = new ForumRoleForumActionRightEntityStaticMetaData();
		private static ForumRoleForumActionRightRelations _relationsFactory = new ForumRoleForumActionRightRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name ActionRight</summary>
			public static readonly string ActionRight = "ActionRight";
			/// <summary>Member name Forum</summary>
			public static readonly string Forum = "Forum";
			/// <summary>Member name Role</summary>
			public static readonly string Role = "Role";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class ForumRoleForumActionRightEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public ForumRoleForumActionRightEntityStaticMetaData()
			{
				SetEntityCoreInfo("ForumRoleForumActionRightEntity", InheritanceHierarchyType.None, false, (int)SD.HnD.DALAdapter.EntityType.ForumRoleForumActionRightEntity, typeof(ForumRoleForumActionRightEntity), typeof(ForumRoleForumActionRightEntityFactory), false);
				AddNavigatorMetaData<ForumRoleForumActionRightEntity, ActionRightEntity>("ActionRight", "ForumRoleForumActionRights", (a, b) => a._actionRight = b, a => a._actionRight, (a, b) => a.ActionRight = b, SD.HnD.DALAdapter.RelationClasses.StaticForumRoleForumActionRightRelations.ActionRightEntityUsingActionRightIDStatic, ()=>new ForumRoleForumActionRightRelations().ActionRightEntityUsingActionRightID, null, new int[] { (int)ForumRoleForumActionRightFieldIndex.ActionRightID }, null, true, (int)SD.HnD.DALAdapter.EntityType.ActionRightEntity);
				AddNavigatorMetaData<ForumRoleForumActionRightEntity, ForumEntity>("Forum", "ForumRoleForumActionRights", (a, b) => a._forum = b, a => a._forum, (a, b) => a.Forum = b, SD.HnD.DALAdapter.RelationClasses.StaticForumRoleForumActionRightRelations.ForumEntityUsingForumIDStatic, ()=>new ForumRoleForumActionRightRelations().ForumEntityUsingForumID, null, new int[] { (int)ForumRoleForumActionRightFieldIndex.ForumID }, null, true, (int)SD.HnD.DALAdapter.EntityType.ForumEntity);
				AddNavigatorMetaData<ForumRoleForumActionRightEntity, RoleEntity>("Role", "ForumRoleForumActionRights", (a, b) => a._role = b, a => a._role, (a, b) => a.Role = b, SD.HnD.DALAdapter.RelationClasses.StaticForumRoleForumActionRightRelations.RoleEntityUsingRoleIDStatic, ()=>new ForumRoleForumActionRightRelations().RoleEntityUsingRoleID, null, new int[] { (int)ForumRoleForumActionRightFieldIndex.RoleID }, null, true, (int)SD.HnD.DALAdapter.EntityType.RoleEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static ForumRoleForumActionRightEntity()
		{
		}

		/// <summary> CTor</summary>
		public ForumRoleForumActionRightEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public ForumRoleForumActionRightEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this ForumRoleForumActionRightEntity</param>
		public ForumRoleForumActionRightEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="forumID">PK value for ForumRoleForumActionRight which data should be fetched into this ForumRoleForumActionRight object</param>
		/// <param name="roleID">PK value for ForumRoleForumActionRight which data should be fetched into this ForumRoleForumActionRight object</param>
		/// <param name="actionRightID">PK value for ForumRoleForumActionRight which data should be fetched into this ForumRoleForumActionRight object</param>
		public ForumRoleForumActionRightEntity(System.Int32 forumID, System.Int32 roleID, System.Int32 actionRightID) : this(forumID, roleID, actionRightID, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="forumID">PK value for ForumRoleForumActionRight which data should be fetched into this ForumRoleForumActionRight object</param>
		/// <param name="roleID">PK value for ForumRoleForumActionRight which data should be fetched into this ForumRoleForumActionRight object</param>
		/// <param name="actionRightID">PK value for ForumRoleForumActionRight which data should be fetched into this ForumRoleForumActionRight object</param>
		/// <param name="validator">The custom validator object for this ForumRoleForumActionRightEntity</param>
		public ForumRoleForumActionRightEntity(System.Int32 forumID, System.Int32 roleID, System.Int32 actionRightID, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.ForumID = forumID;
			this.RoleID = roleID;
			this.ActionRightID = actionRightID;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected ForumRoleForumActionRightEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'ActionRight' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoActionRight() { return CreateRelationInfoForNavigator("ActionRight"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Forum' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoForum() { return CreateRelationInfoForNavigator("Forum"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Role' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoRole() { return CreateRelationInfoForNavigator("Role"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this ForumRoleForumActionRightEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static ForumRoleForumActionRightRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'ActionRight' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathActionRight { get { return _staticMetaData.GetPrefetchPathElement("ActionRight", CommonEntityBase.CreateEntityCollection<ActionRightEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Forum' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathForum { get { return _staticMetaData.GetPrefetchPathElement("Forum", CommonEntityBase.CreateEntityCollection<ForumEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Role' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathRole { get { return _staticMetaData.GetPrefetchPathElement("Role", CommonEntityBase.CreateEntityCollection<RoleEntity>()); } }

		/// <summary>The ForumID property of the Entity ForumRoleForumActionRight<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ForumRoleForumActionRight"."ForumID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		[Required]
		public virtual System.Int32 ForumID
		{
			get { return (System.Int32)GetValue((int)ForumRoleForumActionRightFieldIndex.ForumID, true); }
			set	{ SetValue((int)ForumRoleForumActionRightFieldIndex.ForumID, value); }
		}

		/// <summary>The RoleID property of the Entity ForumRoleForumActionRight<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ForumRoleForumActionRight"."RoleID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		[Required]
		public virtual System.Int32 RoleID
		{
			get { return (System.Int32)GetValue((int)ForumRoleForumActionRightFieldIndex.RoleID, true); }
			set	{ SetValue((int)ForumRoleForumActionRightFieldIndex.RoleID, value); }
		}

		/// <summary>The ActionRightID property of the Entity ForumRoleForumActionRight<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ForumRoleForumActionRight"."ActionRightID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		[Required]
		public virtual System.Int32 ActionRightID
		{
			get { return (System.Int32)GetValue((int)ForumRoleForumActionRightFieldIndex.ActionRightID, true); }
			set	{ SetValue((int)ForumRoleForumActionRightFieldIndex.ActionRightID, value); }
		}

		/// <summary>Gets / sets related entity of type 'ActionRightEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual ActionRightEntity ActionRight
		{
			get { return _actionRight; }
			set { SetSingleRelatedEntityNavigator(value, "ActionRight"); }
		}

		/// <summary>Gets / sets related entity of type 'ForumEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual ForumEntity Forum
		{
			get { return _forum; }
			set { SetSingleRelatedEntityNavigator(value, "Forum"); }
		}

		/// <summary>Gets / sets related entity of type 'RoleEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual RoleEntity Role
		{
			get { return _role; }
			set { SetSingleRelatedEntityNavigator(value, "Role"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace SD.HnD.DALAdapter
{
	public enum ForumRoleForumActionRightFieldIndex
	{
		///<summary>ForumID. </summary>
		ForumID,
		///<summary>RoleID. </summary>
		RoleID,
		///<summary>ActionRightID. </summary>
		ActionRightID,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace SD.HnD.DALAdapter.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: ForumRoleForumActionRight. </summary>
	public partial class ForumRoleForumActionRightRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between ForumRoleForumActionRightEntity and ActionRightEntity over the m:1 relation they have, using the relation between the fields: ForumRoleForumActionRight.ActionRightID - ActionRight.ActionRightID</summary>
		public virtual IEntityRelation ActionRightEntityUsingActionRightID
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "ActionRight", false, new[] { ActionRightFields.ActionRightID, ForumRoleForumActionRightFields.ActionRightID }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ForumRoleForumActionRightEntity and ForumEntity over the m:1 relation they have, using the relation between the fields: ForumRoleForumActionRight.ForumID - Forum.ForumID</summary>
		public virtual IEntityRelation ForumEntityUsingForumID
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Forum", false, new[] { ForumFields.ForumID, ForumRoleForumActionRightFields.ForumID }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ForumRoleForumActionRightEntity and RoleEntity over the m:1 relation they have, using the relation between the fields: ForumRoleForumActionRight.RoleID - Role.RoleID</summary>
		public virtual IEntityRelation RoleEntityUsingRoleID
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Role", false, new[] { RoleFields.RoleID, ForumRoleForumActionRightFields.RoleID }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticForumRoleForumActionRightRelations
	{
		internal static readonly IEntityRelation ActionRightEntityUsingActionRightIDStatic = new ForumRoleForumActionRightRelations().ActionRightEntityUsingActionRightID;
		internal static readonly IEntityRelation ForumEntityUsingForumIDStatic = new ForumRoleForumActionRightRelations().ForumEntityUsingForumID;
		internal static readonly IEntityRelation RoleEntityUsingRoleIDStatic = new ForumRoleForumActionRightRelations().RoleEntityUsingRoleID;

		/// <summary>CTor</summary>
		static StaticForumRoleForumActionRightRelations() { }
	}
}
