//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.7.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using SD.HnD.DALAdapter.HelperClasses;
using SD.HnD.DALAdapter.FactoryClasses;
using SD.HnD.DALAdapter.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace SD.HnD.DALAdapter.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'SupportQueue'.<br/><br/></summary>
	[Serializable]
	public partial class SupportQueueEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private EntityCollection<ForumEntity> _defaultForForums;
		private EntityCollection<SupportQueueThreadEntity> _supportQueueThreads;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static SupportQueueEntityStaticMetaData _staticMetaData = new SupportQueueEntityStaticMetaData();
		private static SupportQueueRelations _relationsFactory = new SupportQueueRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name DefaultForForums</summary>
			public static readonly string DefaultForForums = "DefaultForForums";
			/// <summary>Member name SupportQueueThreads</summary>
			public static readonly string SupportQueueThreads = "SupportQueueThreads";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class SupportQueueEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public SupportQueueEntityStaticMetaData()
			{
				SetEntityCoreInfo("SupportQueueEntity", InheritanceHierarchyType.None, false, (int)SD.HnD.DALAdapter.EntityType.SupportQueueEntity, typeof(SupportQueueEntity), typeof(SupportQueueEntityFactory), false);
				AddNavigatorMetaData<SupportQueueEntity, EntityCollection<ForumEntity>>("DefaultForForums", a => a._defaultForForums, (a, b) => a._defaultForForums = b, a => a.DefaultForForums, () => new SupportQueueRelations().ForumEntityUsingDefaultSupportQueueID, typeof(ForumEntity), (int)SD.HnD.DALAdapter.EntityType.ForumEntity);
				AddNavigatorMetaData<SupportQueueEntity, EntityCollection<SupportQueueThreadEntity>>("SupportQueueThreads", a => a._supportQueueThreads, (a, b) => a._supportQueueThreads = b, a => a.SupportQueueThreads, () => new SupportQueueRelations().SupportQueueThreadEntityUsingQueueID, typeof(SupportQueueThreadEntity), (int)SD.HnD.DALAdapter.EntityType.SupportQueueThreadEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static SupportQueueEntity()
		{
		}

		/// <summary> CTor</summary>
		public SupportQueueEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public SupportQueueEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this SupportQueueEntity</param>
		public SupportQueueEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="queueID">PK value for SupportQueue which data should be fetched into this SupportQueue object</param>
		public SupportQueueEntity(System.Int32 queueID) : this(queueID, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="queueID">PK value for SupportQueue which data should be fetched into this SupportQueue object</param>
		/// <param name="validator">The custom validator object for this SupportQueueEntity</param>
		public SupportQueueEntity(System.Int32 queueID, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.QueueID = queueID;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected SupportQueueEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Forum' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoDefaultForForums() { return CreateRelationInfoForNavigator("DefaultForForums"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'SupportQueueThread' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoSupportQueueThreads() { return CreateRelationInfoForNavigator("SupportQueueThreads"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this SupportQueueEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static SupportQueueRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Forum' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathDefaultForForums { get { return _staticMetaData.GetPrefetchPathElement("DefaultForForums", CommonEntityBase.CreateEntityCollection<ForumEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'SupportQueueThread' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathSupportQueueThreads { get { return _staticMetaData.GetPrefetchPathElement("SupportQueueThreads", CommonEntityBase.CreateEntityCollection<SupportQueueThreadEntity>()); } }

		/// <summary>The QueueID property of the Entity SupportQueue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "SupportQueue"."QueueID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 QueueID
		{
			get { return (System.Int32)GetValue((int)SupportQueueFieldIndex.QueueID, true); }
			set { SetValue((int)SupportQueueFieldIndex.QueueID, value); }		}

		/// <summary>The QueueName property of the Entity SupportQueue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "SupportQueue"."QueueName".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String QueueName
		{
			get { return (System.String)GetValue((int)SupportQueueFieldIndex.QueueName, true); }
			set	{ SetValue((int)SupportQueueFieldIndex.QueueName, value); }
		}

		/// <summary>The QueueDescription property of the Entity SupportQueue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "SupportQueue"."QueueDescription".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 250.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String QueueDescription
		{
			get { return (System.String)GetValue((int)SupportQueueFieldIndex.QueueDescription, true); }
			set	{ SetValue((int)SupportQueueFieldIndex.QueueDescription, value); }
		}

		/// <summary>The OrderNo property of the Entity SupportQueue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "SupportQueue"."OrderNo".<br/>Table field type characteristics (type, precision, scale, length): SmallInt, 5, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int16 OrderNo
		{
			get { return (System.Int16)GetValue((int)SupportQueueFieldIndex.OrderNo, true); }
			set	{ SetValue((int)SupportQueueFieldIndex.OrderNo, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'ForumEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(ForumEntity))]
		public virtual EntityCollection<ForumEntity> DefaultForForums { get { return GetOrCreateEntityCollection<ForumEntity, ForumEntityFactory>("DefaultSupportQueue", true, false, ref _defaultForForums); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'SupportQueueThreadEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(SupportQueueThreadEntity))]
		public virtual EntityCollection<SupportQueueThreadEntity> SupportQueueThreads { get { return GetOrCreateEntityCollection<SupportQueueThreadEntity, SupportQueueThreadEntityFactory>("SupportQueue", true, false, ref _supportQueueThreads); } }

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace SD.HnD.DALAdapter
{
	public enum SupportQueueFieldIndex
	{
		///<summary>QueueID. </summary>
		QueueID,
		///<summary>QueueName. </summary>
		QueueName,
		///<summary>QueueDescription. </summary>
		QueueDescription,
		///<summary>OrderNo. </summary>
		OrderNo,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace SD.HnD.DALAdapter.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: SupportQueue. </summary>
	public partial class SupportQueueRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between SupportQueueEntity and ForumEntity over the 1:n relation they have, using the relation between the fields: SupportQueue.QueueID - Forum.DefaultSupportQueueID</summary>
		public virtual IEntityRelation ForumEntityUsingDefaultSupportQueueID
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "DefaultForForums", true, new[] { SupportQueueFields.QueueID, ForumFields.DefaultSupportQueueID }); }
		}

		/// <summary>Returns a new IEntityRelation object, between SupportQueueEntity and SupportQueueThreadEntity over the 1:n relation they have, using the relation between the fields: SupportQueue.QueueID - SupportQueueThread.QueueID</summary>
		public virtual IEntityRelation SupportQueueThreadEntityUsingQueueID
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "SupportQueueThreads", true, new[] { SupportQueueFields.QueueID, SupportQueueThreadFields.QueueID }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticSupportQueueRelations
	{
		internal static readonly IEntityRelation ForumEntityUsingDefaultSupportQueueIDStatic = new SupportQueueRelations().ForumEntityUsingDefaultSupportQueueID;
		internal static readonly IEntityRelation SupportQueueThreadEntityUsingQueueIDStatic = new SupportQueueRelations().SupportQueueThreadEntityUsingQueueID;

		/// <summary>CTor</summary>
		static StaticSupportQueueRelations() { }
	}
}
