//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.9.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using SD.LLBLGen.Pro.QuerySpec;
using SD.HnD.DALAdapter.HelperClasses;
using SD.LLBLGen.Pro.LinqSupportClasses;

namespace SD.HnD.DTOs.Persistence
{
	/// <summary>Static class for (extension) methods for fetching and projecting instances of SD.HnD.DTOs.DtoClasses.UserInRoleDto from / to the entity model.</summary>
	public static partial class UserInRolePersistence
	{
		private static readonly System.Linq.Expressions.Expression<Func<SD.HnD.DALAdapter.EntityClasses.UserEntity, SD.HnD.DTOs.DtoClasses.UserInRoleDto>> _projectorExpression = CreateProjectionFunc();
		private static readonly Func<SD.HnD.DALAdapter.EntityClasses.UserEntity, SD.HnD.DTOs.DtoClasses.UserInRoleDto> _compiledProjector = CreateProjectionFunc().Compile();
		/// <summary>Linq specific partial method for obtaining projection adjustments for the projection method <see cref="ProjectToUserInRoleDto(System.Linq.IQueryable{SD.HnD.DALAdapter.EntityClasses.UserEntity})"/></summary>
		/// <param name="projectionAdjustments">Set this argument in an implementation of this partial method to a projection lambda similar to the generated projection in <see cref="CreateProjectionFunc"/></param>
		/// <remarks>Linq specific</remarks>
		static partial void GetAdjustmentsForProjectToUserInRoleDto(ref System.Linq.Expressions.Expression<Func<SD.HnD.DALAdapter.EntityClasses.UserEntity, SD.HnD.DTOs.DtoClasses.UserInRoleDto>> projectionAdjustments);
		/// <summary>QuerySpec specific partial method for obtaining projection adjustments for the projection method <see cref="ProjectToUserInRoleDto(EntityQuery{SD.HnD.DALAdapter.EntityClasses.UserEntity}, SD.HnD.DALAdapter.FactoryClasses.QueryFactory)"/></summary>
		/// <param name="projectionAdjustments">Set this argument in an implementation of this partial method to a projection lambda similar to the generated projection in <see cref="ProjectToUserInRoleDto(EntityQuery{SD.HnD.DALAdapter.EntityClasses.UserEntity}, SD.HnD.DALAdapter.FactoryClasses.QueryFactory)"/></param>
		/// <remarks>QuerySpec specific</remarks>
		static partial void GetAdjustmentsForProjectToUserInRoleDtoQs(ref System.Linq.Expressions.Expression<Func<SD.HnD.DTOs.DtoClasses.UserInRoleDto>> projectionAdjustments);
	
		/// <summary>Empty static ctor for triggering initialization of static members in a thread-safe manner</summary>
		static UserInRolePersistence() { }
	
		/// <summary>Extension method which produces a projection to SD.HnD.DTOs.DtoClasses.UserInRoleDto which instances are projected from the 
		/// results of the specified baseQuery, which returns SD.HnD.DALAdapter.EntityClasses.UserEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <returns>IQueryable to retrieve SD.HnD.DTOs.DtoClasses.UserInRoleDto instances</returns>
		public static IQueryable<SD.HnD.DTOs.DtoClasses.UserInRoleDto> ProjectToUserInRoleDto(this IQueryable<SD.HnD.DALAdapter.EntityClasses.UserEntity> baseQuery)
		{
			return baseQuery.Select(_projectorExpression);
		}

		/// <summary>Extension method which produces a projection to SD.HnD.DTOs.DtoClasses.UserInRoleDto which instances are projected from the 
		/// results of the specified baseQuery using QuerySpec, which returns SD.HnD.DALAdapter.EntityClasses.UserEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <param name="qf">The query factory used to create baseQuery.</param>
		/// <returns>DynamicQuery to retrieve SD.HnD.DTOs.DtoClasses.UserInRoleDto instances</returns>
		public static DynamicQuery<SD.HnD.DTOs.DtoClasses.UserInRoleDto> ProjectToUserInRoleDto(this EntityQuery<SD.HnD.DALAdapter.EntityClasses.UserEntity> baseQuery, SD.HnD.DALAdapter.FactoryClasses.QueryFactory qf)
		{
			System.Linq.Expressions.Expression<Func<SD.HnD.DTOs.DtoClasses.UserInRoleDto>> projectionAdjustments = null;
			GetAdjustmentsForProjectToUserInRoleDtoQs(ref projectionAdjustments);
			return qf.Create()
				.From(baseQuery.Select(Projection.Full).As("__BQ"))
				.Select(LinqUtils.MergeProjectionAdjustmentsIntoProjection(() => new SD.HnD.DTOs.DtoClasses.UserInRoleDto()
				{
					AmountOfPostings = UserFields.AmountOfPostings.Source("__BQ").ToValue<Nullable<System.Int32>>(),
					EmailAddress = UserFields.EmailAddress.Source("__BQ").ToValue<System.String>(),
					NickName = UserFields.NickName.Source("__BQ").ToValue<System.String>(),
					UserID = UserFields.UserID.Source("__BQ").ToValue<System.Int32>(),
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegionQS_UserInRole 
	// __LLBLGENPRO_USER_CODE_REGION_END 
				}, projectionAdjustments, false));
		}

		/// <summary>Extension method which produces a projection to SD.HnD.DTOs.DtoClasses.UserInRoleDto which instances are projected from the
		/// SD.HnD.DALAdapter.EntityClasses.UserEntity entity instance specified, the root entity of the derived element returned by this method.</summary>
		/// <param name="entity">The entity to project from.</param>
		/// <returns>SD.HnD.DALAdapter.EntityClasses.UserEntity instance created from the specified entity instance</returns>
		public static SD.HnD.DTOs.DtoClasses.UserInRoleDto ProjectToUserInRoleDto(this SD.HnD.DALAdapter.EntityClasses.UserEntity entity)
		{
			return _compiledProjector(entity);
		}
		
		private static System.Linq.Expressions.Expression<Func<SD.HnD.DALAdapter.EntityClasses.UserEntity, SD.HnD.DTOs.DtoClasses.UserInRoleDto>> CreateProjectionFunc()
		{
			System.Linq.Expressions.Expression<Func<SD.HnD.DALAdapter.EntityClasses.UserEntity, SD.HnD.DTOs.DtoClasses.UserInRoleDto>> mainProjection = p__0 => new SD.HnD.DTOs.DtoClasses.UserInRoleDto()
			{
				AmountOfPostings = p__0.AmountOfPostings,
				EmailAddress = p__0.EmailAddress,
				NickName = p__0.NickName,
				UserID = p__0.UserID,
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegion_UserInRole 
	// __LLBLGENPRO_USER_CODE_REGION_END 
			};
			System.Linq.Expressions.Expression<Func<SD.HnD.DALAdapter.EntityClasses.UserEntity, SD.HnD.DTOs.DtoClasses.UserInRoleDto>> projectionAdjustments = null;
			GetAdjustmentsForProjectToUserInRoleDto(ref projectionAdjustments);
			return LinqUtils.MergeProjectionAdjustmentsIntoProjection(mainProjection, projectionAdjustments, true);
		}
		/// <summary>Creates a primary key predicate to be used in a Where() clause in a Linq query which is executed on the database to fetch the original entity instance the specified <see cref="dto"/> object was projected from.</summary>
		/// <param name="dto">The dto object for which the primary key predicate has to be created for.</param>
		/// <returns>ready to use expression</returns>
		public static System.Linq.Expressions.Expression<Func<SD.HnD.DALAdapter.EntityClasses.UserEntity, bool>> CreatePkPredicate(SD.HnD.DTOs.DtoClasses.UserInRoleDto dto)
		{
			return p__0 => p__0.UserID == dto.UserID;
		}

		/// <summary>Creates a primary key predicate to be used in a Where() clause in a Linq query which is executed on the database to fetch the original entity instances the specified set of <see cref="dtos"/> objects was projected from.</summary>
		/// <param name="dtos">The dto objects for which the primary key predicate has to be created for.</param>
		/// <returns>ready to use expression</returns>
		public static System.Linq.Expressions.Expression<Func<SD.HnD.DALAdapter.EntityClasses.UserEntity, bool>> CreatePkPredicate(IEnumerable<SD.HnD.DTOs.DtoClasses.UserInRoleDto> dtos)
		{
			return p__0 => dtos.Select(p__1=>p__1.UserID).ToList().Contains(p__0.UserID);
		}

		/// <summary>Creates a primary key predicate to be used in a Where() clause in a Linq query on an IEnumerable in-memory set of entity instances to retrieve the original entity instance the specified <see cref="dto"/> object was projected from.</summary>
		/// <param name="dto">The dto object for which the primary key predicate has to be created for.</param>
		/// <returns>ready to use func</returns>
		public static Func<SD.HnD.DALAdapter.EntityClasses.UserEntity, bool> CreateInMemoryPkPredicate(SD.HnD.DTOs.DtoClasses.UserInRoleDto dto)
		{
			return p__0 => p__0.UserID == dto.UserID;
		}
		
		/// <summary>Updates the specified SD.HnD.DALAdapter.EntityClasses.UserEntity entity with the values stored in the dto object specified</summary>
		/// <param name="toUpdate">the entity instance to update.</param>
		/// <param name="dto">The dto object containing the source values.</param>
		/// <remarks>The PK field of toUpdate is set only if it's not marked as readonly.</remarks>
		public static void UpdateFromUserInRole(this SD.HnD.DALAdapter.EntityClasses.UserEntity toUpdate, SD.HnD.DTOs.DtoClasses.UserInRoleDto dto)
		{
			if((toUpdate == null) || (dto == null))
			{
				return;
			}
			toUpdate.AmountOfPostings = dto.AmountOfPostings;
			toUpdate.EmailAddress = dto.EmailAddress;
			toUpdate.NickName = dto.NickName;
		}
	}
}


 