//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.11.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;	

namespace SD.HnD.DTOs.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'Message'.</summary>
	public partial class MessageInThreadDto
	{
		/// <summary>Gets or sets the Attachments field. </summary>
		public List<MessageInThreadDtoTypes.AttachmentDto> Attachments { get; set; }
		/// <summary>Gets or sets the MessageID field. Derived from Entity Model Field 'Message.MessageID'</summary>
		[Required]
		public System.Int32 MessageID { get; set; }
		/// <summary>Gets or sets the MessageTextAsHTML field. Derived from Entity Model Field 'Message.MessageTextAsHTML'</summary>
		public System.String MessageTextAsHTML { get; set; }
		/// <summary>Gets or sets the PostedByUser field. </summary>
		public MessageInThreadDtoTypes.PostedByUserDto PostedByUser { get; set; }
		/// <summary>Gets or sets the PostedFromIP field. Derived from Entity Model Field 'Message.PostedFromIP'</summary>
		[StringLength(25)]
		[Required]
		public System.String PostedFromIP { get; set; }
		/// <summary>Gets or sets the PostingDate field. Derived from Entity Model Field 'Message.PostingDate'</summary>
		[Required]
		public System.DateTime PostingDate { get; set; }
		/// <summary>Gets or sets the ThreadID field. Derived from Entity Model Field 'Message.ThreadID (FK)'</summary>
		[Required]
		public System.Int32 ThreadID { get; set; }
	}

	namespace MessageInThreadDtoTypes
	{
		/// <summary> DTO class which is derived from the entity 'Attachment (Attachments)'.</summary>
		public partial class AttachmentDto
		{
			/// <summary>Gets or sets the AddedOn field. Derived from Entity Model Field 'Attachment.AddedOn'</summary>
			[Required]
			public System.DateTime AddedOn { get; set; }
			/// <summary>Gets or sets the Approved field. Derived from Entity Model Field 'Attachment.Approved'</summary>
			[Required]
			public System.Boolean Approved { get; set; }
			/// <summary>Gets or sets the AttachmentID field. Derived from Entity Model Field 'Attachment.AttachmentID'</summary>
			[Required]
			public System.Int32 AttachmentID { get; set; }
			/// <summary>Gets or sets the Filename field. Derived from Entity Model Field 'Attachment.Filename'</summary>
			[StringLength(255)]
			[Required]
			public System.String Filename { get; set; }
			/// <summary>Gets or sets the Filesize field. Derived from Entity Model Field 'Attachment.Filesize'</summary>
			[Required]
			public System.Int32 Filesize { get; set; }
		}

		/// <summary> DTO class which is derived from the entity 'User (PostedByUser)'.</summary>
		public partial class PostedByUserDto
		{
			/// <summary>Gets or sets the AmountOfPostings field. Derived from Entity Model Field 'User.AmountOfPostings'</summary>
			public Nullable<System.Int32> AmountOfPostings { get; set; }
			/// <summary>Gets or sets the IconURL field. Derived from Entity Model Field 'User.IconURL'</summary>
			[StringLength(250)]
			public System.String IconURL { get; set; }
			/// <summary>Gets or sets the JoinDate field. Derived from Entity Model Field 'User.JoinDate'</summary>
			public Nullable<System.DateTime> JoinDate { get; set; }
			/// <summary>Gets or sets the Location field. Derived from Entity Model Field 'User.Location'</summary>
			[StringLength(100)]
			public System.String Location { get; set; }
			/// <summary>Gets or sets the NickName field. Derived from Entity Model Field 'User.NickName'</summary>
			[StringLength(20)]
			[Required]
			public System.String NickName { get; set; }
			/// <summary>Gets or sets the Signature field. Derived from Entity Model Field 'User.Signature'</summary>
			[StringLength(250)]
			public System.String Signature { get; set; }
			/// <summary>Gets or sets the UserID field. Derived from Entity Model Field 'User.UserID'</summary>
			[Required]
			public System.Int32 UserID { get; set; }
			/// <summary>Gets or sets the UserTitleDescription field. Derived from Entity Model Field 'UserTitle.UserTitleDescription (PostedByUser.UserTitle)'</summary>
			[StringLength(50)]
			[Required]
			public System.String UserTitleDescription { get; set; }
		}
	}

}




