//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.7.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;	

namespace SD.HnD.DTOs.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'Section'.</summary>
	public partial class SectionDto
	{
		/// <summary>Gets or sets the OrderNo field. Derived from Entity Model Field 'Section.OrderNo'</summary>
		[Required]
		public System.Int16 OrderNo { get; set; }
		/// <summary>Gets or sets the SectionDescription field. Derived from Entity Model Field 'Section.SectionDescription'</summary>
		[StringLength(250)]
		[Required]
		public System.String SectionDescription { get; set; }
		/// <summary>Gets or sets the SectionID field. Derived from Entity Model Field 'Section.SectionID'</summary>
		[Required]
		public System.Int32 SectionID { get; set; }
		/// <summary>Gets or sets the SectionName field. Derived from Entity Model Field 'Section.SectionName'</summary>
		[StringLength(50)]
		[Required]
		public System.String SectionName { get; set; }
	}

}




