//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.7.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;	

namespace SD.HnD.DTOs.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'SupportQueue'.</summary>
	public partial class SupportQueueDto
	{
		/// <summary>Gets or sets the OrderNo field. Derived from Entity Model Field 'SupportQueue.OrderNo'</summary>
		[Required]
		public System.Int16 OrderNo { get; set; }
		/// <summary>Gets or sets the QueueDescription field. Derived from Entity Model Field 'SupportQueue.QueueDescription'</summary>
		[StringLength(250)]
		[Required]
		public System.String QueueDescription { get; set; }
		/// <summary>Gets or sets the QueueID field. Derived from Entity Model Field 'SupportQueue.QueueID'</summary>
		[Required]
		public System.Int32 QueueID { get; set; }
		/// <summary>Gets or sets the QueueName field. Derived from Entity Model Field 'SupportQueue.QueueName'</summary>
		[StringLength(50)]
		[Required]
		public System.String QueueName { get; set; }
	}

}




