//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.7.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;	

namespace SD.HnD.DTOs.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'User'.</summary>
	public partial class UserInRoleDto
	{
		/// <summary>Gets or sets the AmountOfPostings field. Derived from Entity Model Field 'User.AmountOfPostings'</summary>
		public Nullable<System.Int32> AmountOfPostings { get; set; }
		/// <summary>Gets or sets the EmailAddress field. Derived from Entity Model Field 'User.EmailAddress'</summary>
		[StringLength(200)]
		public System.String EmailAddress { get; set; }
		/// <summary>Gets or sets the NickName field. Derived from Entity Model Field 'User.NickName'</summary>
		[StringLength(20)]
		[Required]
		public System.String NickName { get; set; }
		/// <summary>Gets or sets the UserID field. Derived from Entity Model Field 'User.UserID'</summary>
		[Required]
		public System.Int32 UserID { get; set; }
	}

}




