//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.11.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;

namespace SD.HnD.DALAdapter
{

	/// <summary>Index enum to fast-access TypedList Fields in the Columns collection of the Typed List: ForumMessages</summary>
	public enum ForumMessagesTypedListFieldIndex
	{
		///<summary>MessageID</summary>
		MessageID,
		///<summary>PostingDate</summary>
		PostingDate,
		///<summary>MessageTextAsHTML</summary>
		MessageTextAsHTML,
		///<summary>ThreadID</summary>
		ThreadID,
		///<summary>Subject</summary>
		Subject,
		///<summary>EmailAddress</summary>
		EmailAddress,
		///<summary>EmailAddressIsPublic</summary>
		EmailAddressIsPublic,
		///<summary>NickName</summary>
		NickName,
		///<summary>MessageText</summary>
		MessageText,
		/// <summary></summary>
		AmountOfFields
	}
	/// <summary>Index enum to fast-access TypedList Fields in the Columns collection of the Typed List: ForumsWithSectionName</summary>
	public enum ForumsWithSectionNameTypedListFieldIndex
	{
		///<summary>ForumID</summary>
		ForumID,
		///<summary>ForumName</summary>
		ForumName,
		///<summary>SectionName</summary>
		SectionName,
		///<summary>ForumDescription</summary>
		ForumDescription,
		///<summary>SectionID</summary>
		SectionID,
		///<summary>ForumOrderNo</summary>
		ForumOrderNo,
		/// <summary></summary>
		AmountOfFields
	}
	/// <summary>Index enum to fast-access TypedList Fields in the Columns collection of the Typed List: SearchResult</summary>
	public enum SearchResultTypedListFieldIndex
	{
		///<summary>ThreadID</summary>
		ThreadID,
		///<summary>Subject</summary>
		Subject,
		///<summary>ForumName</summary>
		ForumName,
		///<summary>SectionName</summary>
		SectionName,
		///<summary>ThreadLastPostingDate</summary>
		ThreadLastPostingDate,
		/// <summary></summary>
		AmountOfFields
	}
	/// <summary>Index enum to fast-access TypedList Fields in the Columns collection of the Typed List: UserProfileInfo</summary>
	public enum UserProfileInfoTypedListFieldIndex
	{
		///<summary>AmountOfPostings</summary>
		AmountOfPostings,
		///<summary>DateOfBirth</summary>
		DateOfBirth,
		///<summary>EmailAddress</summary>
		EmailAddress,
		///<summary>EmailAddressIsPublic</summary>
		EmailAddressIsPublic,
		///<summary>IconURL</summary>
		IconURL,
		///<summary>IPNumber</summary>
		IPNumber,
		///<summary>IsBanned</summary>
		IsBanned,
		///<summary>JoinDate</summary>
		JoinDate,
		///<summary>LastVisitedDate</summary>
		LastVisitedDate,
		///<summary>Location</summary>
		Location,
		///<summary>NickName</summary>
		NickName,
		///<summary>Occupation</summary>
		Occupation,
		///<summary>Signature</summary>
		Signature,
		///<summary>UserID</summary>
		UserID,
		///<summary>Website</summary>
		Website,
		///<summary>UserTitleDescription</summary>
		UserTitleDescription,
		/// <summary></summary>
		AmountOfFields
	}

	/// <summary>Enum definition for all the entity types defined in this namespace. Used by the entityfields factory.</summary>
	public enum EntityType
	{
		///<summary>ActionRight</summary>
		ActionRightEntity,
		///<summary>Attachment</summary>
		AttachmentEntity,
		///<summary>AuditAction</summary>
		AuditActionEntity,
		///<summary>AuditDataCore</summary>
		AuditDataCoreEntity,
		///<summary>AuditDataMessageRelated</summary>
		AuditDataMessageRelatedEntity,
		///<summary>AuditDataThreadRelated</summary>
		AuditDataThreadRelatedEntity,
		///<summary>Bookmark</summary>
		BookmarkEntity,
		///<summary>Forum</summary>
		ForumEntity,
		///<summary>ForumRoleForumActionRight</summary>
		ForumRoleForumActionRightEntity,
		///<summary>IPBan</summary>
		IPBanEntity,
		///<summary>Message</summary>
		MessageEntity,
		///<summary>PasswordResetToken</summary>
		PasswordResetTokenEntity,
		///<summary>Role</summary>
		RoleEntity,
		///<summary>RoleAuditAction</summary>
		RoleAuditActionEntity,
		///<summary>RoleSystemActionRight</summary>
		RoleSystemActionRightEntity,
		///<summary>RoleUser</summary>
		RoleUserEntity,
		///<summary>Section</summary>
		SectionEntity,
		///<summary>SupportQueue</summary>
		SupportQueueEntity,
		///<summary>SupportQueueThread</summary>
		SupportQueueThreadEntity,
		///<summary>SystemData</summary>
		SystemDataEntity,
		///<summary>Thread</summary>
		ThreadEntity,
		///<summary>ThreadStatistics</summary>
		ThreadStatisticsEntity,
		///<summary>ThreadSubscription</summary>
		ThreadSubscriptionEntity,
		///<summary>User</summary>
		UserEntity,
		///<summary>UserTitle</summary>
		UserTitleEntity
	}



	// __LLBLGENPRO_USER_CODE_REGION_START CustomUserConstants
	// __LLBLGENPRO_USER_CODE_REGION_END

}

